%
% Get an array of colors
%
% @return Array of colors
%
function [colors] = getColors()
    colors = [...
        'y' ; ...
        'm' ; ...
        'c' ; ...
        'r' ; ...
        'g' ; ...
        'b' ; ...
        'w' ; ...
        'b'   ...
    ];
end